---
- hosts: piHole
  tasks:
    - name: Updating FTL
      become: true
      become_method: sudo
      remote_user: root
      shell: pihole -up
      args:
        warn: false

    - name: Updating Gravity
      shell: pihole -g
      args:
        warn: false
        
- hosts: piHole,UpdateAndNoReboot
  tasks:
    - name: Updating all packages
      apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes
        cache_valid_time: 3600
        autoremove: yes
        autoclean: yes
