---
- hosts: pihole
  tasks:
    - name: Updating FTL
      ansible.builtin.command: pihole -up
      args:
        warn: false

    - name: Updating Gravity
      ansible.builtin.command: pihole -g
      args:
        warn: false
        
- hosts: pihole,UpdateAndNoReboot
  tasks:
    - name: Updating all packages
      apt:
        update_cache: yes
        upgrade: yes
        force_apt_get: yes
        cache_valid_time: 3600
        autoremove: yes
        autoclean: yes
